# Generated by Django 5.0.2 on 2024-03-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0007_alter_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-posta'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='isim soyisim'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='mesaj'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='telefon'),
        ),
    ]
